Fix bug in Embed mode
In Embed mode, the categoryIds and tagID's are not always (ever?) valid key names for the json array.
I have added null check so that these elements are ignored when null, as they currently cause the following exception:

errors.dart:147 Uncaught (in promise) Error: NoSuchMethodError: 'cast'